version: '3.8'

services:
  scraper:    
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - proxy
    links:
      - proxy
    env_file:
      - .env
  proxy:    
    image: proxy_test
    env_file:
      - .env_proxy