# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scraper/v1/scraper.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scraper/v1/scraper.proto',
  package='scraper.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18scraper/v1/scraper.proto\x12\nscraper.v1\"G\n\x0eGetHtmlRequest\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\x12#\n\rproxy_address\x18\x02 \x01(\tR\x0cproxyAddress\"%\n\x0fGetHtmlResponse\x12\x12\n\x04html\x18\x01 \x01(\tR\x04html2V\n\x0eScraperService\x12\x44\n\x07GetHtml\x12\x1a.scraper.v1.GetHtmlRequest\x1a\x1b.scraper.v1.GetHtmlResponse\"\x00\x62\x06proto3'
)




_GETHTMLREQUEST = _descriptor.Descriptor(
  name='GetHtmlRequest',
  full_name='scraper.v1.GetHtmlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='scraper.v1.GetHtmlRequest.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='url', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='proxy_address', full_name='scraper.v1.GetHtmlRequest.proxy_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='proxyAddress', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=111,
)


_GETHTMLRESPONSE = _descriptor.Descriptor(
  name='GetHtmlResponse',
  full_name='scraper.v1.GetHtmlResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='html', full_name='scraper.v1.GetHtmlResponse.html', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='html', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['GetHtmlRequest'] = _GETHTMLREQUEST
DESCRIPTOR.message_types_by_name['GetHtmlResponse'] = _GETHTMLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetHtmlRequest = _reflection.GeneratedProtocolMessageType('GetHtmlRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETHTMLREQUEST,
  '__module__' : 'scraper.v1.scraper_pb2'
  # @@protoc_insertion_point(class_scope:scraper.v1.GetHtmlRequest)
  })
_sym_db.RegisterMessage(GetHtmlRequest)

GetHtmlResponse = _reflection.GeneratedProtocolMessageType('GetHtmlResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETHTMLRESPONSE,
  '__module__' : 'scraper.v1.scraper_pb2'
  # @@protoc_insertion_point(class_scope:scraper.v1.GetHtmlResponse)
  })
_sym_db.RegisterMessage(GetHtmlResponse)



_SCRAPERSERVICE = _descriptor.ServiceDescriptor(
  name='ScraperService',
  full_name='scraper.v1.ScraperService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=152,
  serialized_end=238,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetHtml',
    full_name='scraper.v1.ScraperService.GetHtml',
    index=0,
    containing_service=None,
    input_type=_GETHTMLREQUEST,
    output_type=_GETHTMLRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCRAPERSERVICE)

DESCRIPTOR.services_by_name['ScraperService'] = _SCRAPERSERVICE

# @@protoc_insertion_point(module_scope)
