# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import scraper_pb2 as scraper__pb2


class ScraperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHtml = channel.unary_unary(
                '/scraper.v1.ScraperService/GetHtml',
                request_serializer=scraper__pb2.GetHtmlRequest.SerializeToString,
                response_deserializer=scraper__pb2.GetHtmlResponse.FromString,
                )


class ScraperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHtml(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScraperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHtml': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHtml,
                    request_deserializer=scraper__pb2.GetHtmlRequest.FromString,
                    response_serializer=scraper__pb2.GetHtmlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scraper.v1.ScraperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScraperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHtml(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scraper.v1.ScraperService/GetHtml',
            scraper__pb2.GetHtmlRequest.SerializeToString,
            scraper__pb2.GetHtmlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)