# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from scraper.proto.scraper.v1 import scraper_pb2 as scraper_dot_v1_dot_scraper__pb2


class ScraperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Test = channel.unary_unary(
                '/scraper.v1.ScraperService/Test',
                request_serializer=scraper_dot_v1_dot_scraper__pb2.TestRequest.SerializeToString,
                response_deserializer=scraper_dot_v1_dot_scraper__pb2.TestResponse.FromString,
                )
        self.Run = channel.unary_unary(
                '/scraper.v1.ScraperService/Run',
                request_serializer=scraper_dot_v1_dot_scraper__pb2.RunRequest.SerializeToString,
                response_deserializer=scraper_dot_v1_dot_scraper__pb2.RunResponse.FromString,
                )


class ScraperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Test(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Run(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScraperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Test': grpc.unary_unary_rpc_method_handler(
                    servicer.Test,
                    request_deserializer=scraper_dot_v1_dot_scraper__pb2.TestRequest.FromString,
                    response_serializer=scraper_dot_v1_dot_scraper__pb2.TestResponse.SerializeToString,
            ),
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=scraper_dot_v1_dot_scraper__pb2.RunRequest.FromString,
                    response_serializer=scraper_dot_v1_dot_scraper__pb2.RunResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scraper.v1.ScraperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ScraperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Test(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scraper.v1.ScraperService/Test',
            scraper_dot_v1_dot_scraper__pb2.TestRequest.SerializeToString,
            scraper_dot_v1_dot_scraper__pb2.TestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scraper.v1.ScraperService/Run',
            scraper_dot_v1_dot_scraper__pb2.RunRequest.SerializeToString,
            scraper_dot_v1_dot_scraper__pb2.RunResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
