
name: LSB-SCRAPER CI

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      with:
        images: $ECR_REGISTRY/lsb-scraper
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG_V: ${{ steps.get_version.outputs.VERSION }}
      run: |
        echo $IMAGE
        docker build -t $ECR_REGISTRY/lsb-scraper:$IMAGE_TAG_V  .
        docker push $ECR_REGISTRY/lsb-scraper:$IMAGE_TAG_V 
